INSERT INTO manager(name, phone, dni) VALUES('Patricia Lopez', 666777888, '44444444P');
INSERT INTO manager(name, phone, dni) VALUES('Arturo Puente', 666555888, '55555555P');
INSERT INTO manager(name, phone, dni) VALUES('Silvia Ferrandez', 666777999, '88888888P');
INSERT INTO manager(name, phone, dni) VALUES('Tamara Rodriguez', 666444111, '999999999T');
INSERT INTO manager(name, phone, dni) VALUES('Alvaro Cruz', 666333555, '11111111D');
INSERT INTO manager(name, phone, dni) VALUES('Virginia Sanchez', 666333222, '22222222C');
INSERT INTO manager(name, phone, dni) VALUES('Paco Martinez', 666777111, '33333333B');
INSERT INTO manager(name, phone, dni) VALUES('Elisabeth Ruiz', 666222111, '123456789A');
INSERT INTO manager(name, phone, dni) VALUES('Raul Macia', 666222555, '123456789E');
INSERT INTO manager(name, phone, dni) VALUES('Maria Maldonado', 666222333, '123456789J');

INSERT INTO host(name, site, manager_id) VALUES ('Ayuntamiento', 'Elche', 1);
INSERT INTO host(name, site, manager_id) VALUES ('Pedania Altabix', 'Altabix', 2);
INSERT INTO host(name, site, manager_id) VALUES ('Pedania Torrellano', 'Torrellano', 3);
INSERT INTO host(name, site, manager_id) VALUES ('Pedania La Hoya', 'La Hoya', 4);
INSERT INTO host(name, site, manager_id) VALUES ('Pedania Las Bayas', 'Las Bayas', 5);
INSERT INTO host(name, site, manager_id) VALUES ('Pedania Matola', 'Matola', 6);
INSERT INTO host(name, site, manager_id) VALUES ('Pedania Arenales', 'Arenales', 7);
INSERT INTO host(name, site, manager_id) VALUES ('Pedania Altet', 'Altet', 8);
INSERT INTO host(name, site, manager_id) VALUES ('Pedania La Marina', 'La Marina', 9);
INSERT INTO host(name, site, manager_id) VALUES ('Pedania Algoda', 'Algoda', 10);

insert into event (name, date, fences, signals, host_id) values ('Osinski and Sons', '2023-07-28', 7, 22, 3);
insert into event (name, date, fences, signals, host_id) values ('Rosenbaum-Green', '2023-02-01', 113, 35, 3);
insert into event (name, date, fences, signals, host_id) values ('Osinski, Baumbach and Cartwright', '2023-02-06', 54, 101, 3);
insert into event (name, date, fences, signals, host_id) values ('Stiedemann LLC', '2023-09-01', 85, 38, 7);
insert into event (name, date, fences, signals, host_id) values ('Jakubowski LLC', '2023-12-03', 88, 116, 8);
insert into event (name, date, fences, signals, host_id) values ('Torp-Kshlerin', '2023-10-12', 86, 106, 2);
insert into event (name, date, fences, signals, host_id) values ('VonRueden Group', '2023-10-13', 21, 131, 9);
insert into event (name, date, fences, signals, host_id) values ('Pollich-Rohan', '2023-04-03', 264, 52, 7);
insert into event (name, date, fences, signals, host_id) values ('Simonis, Gulgowski and McGlynn', '2023-04-10', 205, 90, 8);
insert into event (name, date, fences, signals, host_id) values ('Wyman Inc', '2023-07-14', 58, 177, 10);
insert into event (name, date, fences, signals, host_id) values ('Casper, Bergstrom and Ferry', '2023-02-01', 161, 103, 8);
insert into event (name, date, fences, signals, host_id) values ('Bernhard Inc', '2023-12-30', 28, 10, 5);
insert into event (name, date, fences, signals, host_id) values ('Gottlieb Group', '2023-03-15', 27, 81, 2);
insert into event (name, date, fences, signals, host_id) values ('Bode-Hammes', '2023-10-26', 245, 145, 1);
insert into event (name, date, fences, signals, host_id) values ('Dickens Inc', '2023-07-27', 82, 90, 9);
insert into event (name, date, fences, signals, host_id) values ('Reinger Inc', '2023-10-18', 264, 37, 3);
insert into event (name, date, fences, signals, host_id) values ('Waelchi LLC', '2023-07-19', 79, 9, 5);
insert into event (name, date, fences, signals, host_id) values ('Hills, Renner and Lind', '2024-01-27', 189, 135, 10);
insert into event (name, date, fences, signals, host_id) values ('Kulas-Considine', '2023-12-22', 43, 113, 4);
insert into event (name, date, fences, signals, host_id) values ('Hansen and Sons', '2023-05-16', 165, 58, 2);
insert into event (name, date, fences, signals, host_id) values ('Senger-Pfannerstill', '2023-08-29', 265, 55, 5);
insert into event (name, date, fences, signals, host_id) values ('Barrows Inc', '2023-09-13', 198, 20, 2);
insert into event (name, date, fences, signals, host_id) values ('Wehner, Kohler and Fahey', '2024-01-07', 243, 10, 9);
insert into event (name, date, fences, signals, host_id) values ('Jacobs-Toy', '2023-11-24', 49, 179, 8);
insert into event (name, date, fences, signals, host_id) values ('Gutmann-Will', '2023-09-22', 235, 118, 5);
insert into event (name, date, fences, signals, host_id) values ('Skiles-Kohler', '2023-04-21', 75, 155, 8);
insert into event (name, date, fences, signals, host_id) values ('Hane, Mitchell and Breitenberg', '2023-07-09', 259, 27, 6);
insert into event (name, date, fences, signals, host_id) values ('Hermann, Sanford and Harris', '2023-02-26', 219, 181, 2);
insert into event (name, date, fences, signals, host_id) values ('Keeling Group', '2023-10-22', 66, 98, 4);
insert into event (name, date, fences, signals, host_id) values ('Kautzer LLC', '2023-08-30', 42, 130, 9);
insert into event (name, date, fences, signals, host_id) values ('Abbott and Sons', '2023-07-07', 18, 200, 10);
insert into event (name, date, fences, signals, host_id) values ('D''Amore-Breitenberg', '2023-08-17', 179, 174, 3);
insert into event (name, date, fences, signals, host_id) values ('Waelchi, Marvin and Hauck', '2023-08-01', 127, 102, 10);
insert into event (name, date, fences, signals, host_id) values ('Wiegand-Mante', '2023-03-06', 126, 83, 7);
insert into event (name, date, fences, signals, host_id) values ('Harris, Medhurst and Price', '2023-07-30', 250, 102, 10);
insert into event (name, date, fences, signals, host_id) values ('Ratke-Dickens', '2023-11-30', 193, 6, 5);
insert into event (name, date, fences, signals, host_id) values ('Lubowitz, Hudson and Sauer', '2023-11-15', 211, 35, 4);
insert into event (name, date, fences, signals, host_id) values ('Jakubowski, Koepp and Kuphal', '2023-12-29', 198, 87, 7);
insert into event (name, date, fences, signals, host_id) values ('Rosenbaum LLC', '2023-06-21', 218, 83, 9);
insert into event (name, date, fences, signals, host_id) values ('Miller, Kulas and Johnston', '2023-09-18', 242, 48, 2);
insert into event (name, date, fences, signals, host_id) values ('Casper-Treutel', '2023-04-17', 110, 182, 5);
insert into event (name, date, fences, signals, host_id) values ('Brown Group', '2023-02-07', 132, 20, 7);
insert into event (name, date, fences, signals, host_id) values ('Berge-McGlynn', '2024-01-07', 5, 40, 8);
insert into event (name, date, fences, signals, host_id) values ('Larkin-Hettinger', '2024-01-01', 87, 12, 8);
insert into event (name, date, fences, signals, host_id) values ('Marquardt, Wiza and Rutherford', '2023-03-06', 157, 60, 6);
insert into event (name, date, fences, signals, host_id) values ('Blick LLC', '2023-03-16', 64, 109, 1);
insert into event (name, date, fences, signals, host_id) values ('Bednar Inc', '2023-08-06', 151, 192, 9);
insert into event (name, date, fences, signals, host_id) values ('Connelly Group', '2023-07-07', 40, 141, 3);
insert into event (name, date, fences, signals, host_id) values ('Wolf and Sons', '2023-12-02', 43, 109, 2);
insert into event (name, date, fences, signals, host_id) values ('Wolf-Welch', '2023-08-02', 174, 84, 2);

insert into personal (name, type, dni) values ('Saul Gethouse', 'AYTO', '123456789B');
insert into personal (name, type, dni) values ('Carly Werndly', 'PL', '88999000I');
insert into personal (name, type, dni) values ('Gaylord Cadwell', 'VOL', '66777888G');
insert into personal (name, type, dni) values ('Erica Grewe', 'AYTO', '44555666E');
insert into personal (name, type, dni) values ('Mike Fairest', 'VOL', '55666777F');
insert into personal (name, type, dni) values ('Horace McCafferky', 'VOL', '22333444C');
insert into personal (name, type, dni) values ('Franny Dunleavy', 'PC', '33444555D');
insert into personal (name, type, dni) values ('Valina Sibborn', 'MU', '33444555D');
insert into personal (name, type, dni) values ('Holli Poznanski', 'VOL', '88999000I');
insert into personal (name, type, dni) values ('Shaine Vizard', 'VOL', '88999000I');
insert into personal (name, type, dni) values ('Ophelie Varnham', 'PC', '55666777F');
insert into personal (name, type, dni) values ('Lucine Stringfellow', 'PL', '44555666E');
insert into personal (name, type, dni) values ('Janith Cromie', 'AYTO', '123456789B');
insert into personal (name, type, dni) values ('Emerson Vince', 'MU', '44555666E');
insert into personal (name, type, dni) values ('Francisco Wellsman', 'PC', '11111111A');
insert into personal (name, type, dni) values ('Mady Rowan', 'AYTO', '77888999H');
insert into personal (name, type, dni) values ('Orrin Dighton', 'VOL', '66777888G');
insert into personal (name, type, dni) values ('Edwin McCane', 'PC', '66777888G');
insert into personal (name, type, dni) values ('Ethelda Rouchy', 'PC', '88999000I');
insert into personal (name, type, dni) values ('Chauncey Cordet', 'MU', '77888999H');
insert into personal (name, type, dni) values ('Holmes Winckles', 'PL', '123456789B');
insert into personal (name, type, dni) values ('Fredra Saul', 'MU', '77888999H');
insert into personal (name, type, dni) values ('Valerie Mosten', 'MU', '88999000I');
insert into personal (name, type, dni) values ('Bendicty Ibotson', 'PL', '55666777F');
insert into personal (name, type, dni) values ('Chariot Massow', 'MU', '123456789B');
insert into personal (name, type, dni) values ('Malissa Gritsaev', 'PC', '44555666E');
insert into personal (name, type, dni) values ('Leroy Snelson', 'PC', '77888999H');
insert into personal (name, type, dni) values ('Nevins Reubel', 'PL', '33444555D');
insert into personal (name, type, dni) values ('Randi M''Barron', 'MU', '99000111K');
insert into personal (name, type, dni) values ('Cornell Behrendsen', 'VOL', '66777888G');
insert into personal (name, type, dni) values ('Morissa Geldert', 'MU', '22333444C');
insert into personal (name, type, dni) values ('Chiarra Adney', 'PC', '11111111A');
insert into personal (name, type, dni) values ('Devi Dolohunty', 'AYTO', '22333444C');
insert into personal (name, type, dni) values ('Luther Laughren', 'MU', '55666777F');
insert into personal (name, type, dni) values ('Stern Tuttle', 'PL', '44555666E');
insert into personal (name, type, dni) values ('Arabella Hacker', 'PL', '99000111K');
insert into personal (name, type, dni) values ('Jodi Piolli', 'AYTO', '66777888G');
insert into personal (name, type, dni) values ('Howie Dur', 'MU', '88999000I');
insert into personal (name, type, dni) values ('Patrizius Thebe', 'PC', '123456789B');
insert into personal (name, type, dni) values ('Tedda Mence', 'MU', '44555666E');
insert into personal (name, type, dni) values ('Jaynell Limpenny', 'AYTO', '77888999H');
insert into personal (name, type, dni) values ('Reece Hollibone', 'VOL', '123456789B');
insert into personal (name, type, dni) values ('Sofie Fussell', 'AYTO', '88999000I');
insert into personal (name, type, dni) values ('Keen Coopman', 'VOL', '123456789B');
insert into personal (name, type, dni) values ('Nata Sall', 'PL', '55666777F');
insert into personal (name, type, dni) values ('Leisha Woolbrook', 'VOL', '88999000I');
insert into personal (name, type, dni) values ('Brinn Peploe', 'MU', '22333444C');
insert into personal (name, type, dni) values ('Jessie Ballston', 'PC', '88999000I');
insert into personal (name, type, dni) values ('Adham Lohrensen', 'VOL', '66777888G');
insert into personal (name, type, dni) values ('Mallory Adlam', 'PC', '11111111A');
insert into personal (name, type, dni) values ('Caro Alliberton', 'PC', '99000111K');
insert into personal (name, type, dni) values ('Sascha Howcroft', 'PC', '44555666E');
insert into personal (name, type, dni) values ('Nita Tieman', 'MU', '55666777F');
insert into personal (name, type, dni) values ('Georgianna Melly', 'MU', '123456789B');
insert into personal (name, type, dni) values ('Judie Ariss', 'MU', '55666777F');
insert into personal (name, type, dni) values ('Link Quinane', 'AYTO', '88999000I');
insert into personal (name, type, dni) values ('Minny Buckmaster', 'PL', '99000111K');
insert into personal (name, type, dni) values ('Woodie Aslin', 'PC', '55666777F');
insert into personal (name, type, dni) values ('Arleen Owbridge', 'VOL', '55666777F');
insert into personal (name, type, dni) values ('Lovell Whyffen', 'AYTO', '55666777F');
insert into personal (name, type, dni) values ('Averyl Kivlehan', 'VOL', '55666777F');
insert into personal (name, type, dni) values ('Griselda Whitrod', 'VOL', '88999000I');
insert into personal (name, type, dni) values ('Piggy Currington', 'PC', '77888999H');
insert into personal (name, type, dni) values ('Hi Bothwell', 'PC', '33444555D');
insert into personal (name, type, dni) values ('Titus Somersett', 'AYTO', '33444555D');
insert into personal (name, type, dni) values ('Stirling Dover', 'MU', '99000111K');
insert into personal (name, type, dni) values ('Belinda Lelliott', 'PL', '11111111A');
insert into personal (name, type, dni) values ('Harlan Dog', 'PC', '55666777F');
insert into personal (name, type, dni) values ('Rudolf Carlens', 'AYTO', '22333444C');
insert into personal (name, type, dni) values ('Jeanna Lopes', 'PL', '88999000I');
insert into personal (name, type, dni) values ('Lauren Pidwell', 'PL', '44555666E');
insert into personal (name, type, dni) values ('Doreen Kindread', 'MU', '99000111K');
insert into personal (name, type, dni) values ('Josefina Halladey', 'PC', '33444555D');
insert into personal (name, type, dni) values ('Tamqrah Tayler', 'VOL', '66777888G');
insert into personal (name, type, dni) values ('Sabina Davidovitz', 'PC', '77888999H');
insert into personal (name, type, dni) values ('Verina Triggs', 'PL', '123456789B');
insert into personal (name, type, dni) values ('Clark Hewkin', 'PL', '33444555D');
insert into personal (name, type, dni) values ('Matilde McCord', 'PL', '22333444C');
insert into personal (name, type, dni) values ('Frances Shannahan', 'VOL', '66777888G');
insert into personal (name, type, dni) values ('Niko Trowell', 'VOL', '44555666E');
insert into personal (name, type, dni) values ('Gherardo Cristofaro', 'PL', '99000111K');
insert into personal (name, type, dni) values ('Aleen Nobes', 'AYTO', '123456789B');
insert into personal (name, type, dni) values ('Garvin Godilington', 'PC', '99000111K');
insert into personal (name, type, dni) values ('Deni Stonall', 'PL', '33444555D');
insert into personal (name, type, dni) values ('Ethelda Reignolds', 'PL', '77888999H');
insert into personal (name, type, dni) values ('Alidia Cockshoot', 'MU', '55666777F');
insert into personal (name, type, dni) values ('Todd Pesselt', 'PC', '44555666E');
insert into personal (name, type, dni) values ('Lemmie April', 'VOL', '66777888G');
insert into personal (name, type, dni) values ('Luce Tappington', 'AYTO', '88999000I');
insert into personal (name, type, dni) values ('Astra Calver', 'AYTO', '99000111K');
insert into personal (name, type, dni) values ('Malynda Redit', 'MU', '77888999H');
insert into personal (name, type, dni) values ('Shaylyn Quare', 'AYTO', '66777888G');
insert into personal (name, type, dni) values ('Salem Mongeot', 'MU', '99000111K');
insert into personal (name, type, dni) values ('Kenneth Le Monnier', 'PC', '22333444C');
insert into personal (name, type, dni) values ('Sim Dacre', 'PC', '33444555D');
insert into personal (name, type, dni) values ('Demeter Charlwood', 'MU', '99000111K');
insert into personal (name, type, dni) values ('Muriel Jenik', 'PL', '55666777F');
insert into personal (name, type, dni) values ('Shayla Haimes', 'MU', '88999000I');
insert into personal (name, type, dni) values ('Chane Suggett', 'PC', '99000111K');
insert into personal (name, type, dni) values ('Barry Wheldon', 'PC', '44555666E');
insert into personal (name, type, dni) values ('Vic Spendlove', 'MU', '123456789B');
insert into personal (name, type, dni) values ('Nefen Aleswell', 'AYTO', '77888999H');
insert into personal (name, type, dni) values ('Pasquale Mattityahou', 'PL', '77888999H');
insert into personal (name, type, dni) values ('Brandea Burnsyde', 'PL', '99000111K');
insert into personal (name, type, dni) values ('Ricca Garbett', 'AYTO', '33444555D');
insert into personal (name, type, dni) values ('Vanna Bollins', 'VOL', '44555666E');
insert into personal (name, type, dni) values ('Giuseppe Fearney', 'AYTO', '11111111A');
insert into personal (name, type, dni) values ('Blondy Killick', 'VOL', '66777888G');
insert into personal (name, type, dni) values ('Hendrik Trimmill', 'PC', '33444555D');
insert into personal (name, type, dni) values ('Row Laux', 'PL', '44555666E');
insert into personal (name, type, dni) values ('Ignazio Samarth', 'PC', '55666777F');
insert into personal (name, type, dni) values ('Shanna Kaveney', 'PC', '77888999H');
insert into personal (name, type, dni) values ('Marian Dursley', 'PL', '99000111K');
insert into personal (name, type, dni) values ('Karyl Bean', 'VOL', '77888999H');
insert into personal (name, type, dni) values ('Micheil Rookesby', 'PL', '44555666E');
insert into personal (name, type, dni) values ('Hephzibah Zoppie', 'PL', '22333444C');
insert into personal (name, type, dni) values ('Liam Gaveltone', 'VOL', '55666777F');
insert into personal (name, type, dni) values ('Kaia Quincey', 'VOL', '99000111K');
insert into personal (name, type, dni) values ('Devina Cron', 'AYTO', '33444555D');
insert into personal (name, type, dni) values ('Barbey Menier', 'PC', '123456789B');
insert into personal (name, type, dni) values ('Trevar Bassano', 'PL', '88999000I');
insert into personal (name, type, dni) values ('Rafe Drawmer', 'AYTO', '44555666E');
insert into personal (name, type, dni) values ('Raimund Geram', 'PL', '123456789B');
insert into personal (name, type, dni) values ('Farrel Beardsworth', 'PC', '123456789B');
insert into personal (name, type, dni) values ('Bert Foxon', 'PC', '55666777F');
insert into personal (name, type, dni) values ('Napoleon Greenrod', 'PL', '123456789B');
insert into personal (name, type, dni) values ('Wendall Grimsley', 'AYTO', '88999000I');
insert into personal (name, type, dni) values ('Whitney Kinneally', 'VOL', '123456789B');
insert into personal (name, type, dni) values ('Ferne Reedshaw', 'MU', '88999000I');
insert into personal (name, type, dni) values ('Corliss Thunnercliff', 'PC', '66777888G');
insert into personal (name, type, dni) values ('Berkie Meffen', 'PC', '44555666E');
insert into personal (name, type, dni) values ('Magdalena Denis', 'AYTO', '123456789B');
insert into personal (name, type, dni) values ('Page Swinnerton', 'VOL', '33444555D');
insert into personal (name, type, dni) values ('Rosco Miliffe', 'PL', '77888999H');
insert into personal (name, type, dni) values ('Alexa Pincott', 'PL', '88999000I');
insert into personal (name, type, dni) values ('Jerrie Tuckett', 'PL', '11111111A');
insert into personal (name, type, dni) values ('Tess Scriviner', 'MU', '55666777F');
insert into personal (name, type, dni) values ('Dasya Belliveau', 'PC', '33444555D');
insert into personal (name, type, dni) values ('Beatriz Westcott', 'MU', '88999000I');
insert into personal (name, type, dni) values ('Sondra Moring', 'AYTO', '33444555D');
insert into personal (name, type, dni) values ('Angelita Chisolm', 'AYTO', '88999000I');
insert into personal (name, type, dni) values ('Tillie Ellis', 'PC', '22333444C');
insert into personal (name, type, dni) values ('Jase Fallowes', 'VOL', '99000111K');
insert into personal (name, type, dni) values ('Rod Sibylla', 'VOL', '55666777F');
insert into personal (name, type, dni) values ('Reggie Tommei', 'MU', '11111111A');
insert into personal (name, type, dni) values ('Devon Treadway', 'PC', '77888999H');
insert into personal (name, type, dni) values ('Marion Bustard', 'VOL', '88999000I');
insert into personal (name, type, dni) values ('Janina Dearell', 'VOL', '88999000I');
insert into personal (name, type, dni) values ('Reggi Skitt', 'PC', '44555666E');
insert into personal (name, type, dni) values ('Derward Bundy', 'PC', '123456789B');
insert into personal (name, type, dni) values ('Nappy Barnshaw', 'PL', '99000111K');
insert into personal (name, type, dni) values ('Scotty Oakenford', 'PC', '123456789B');
insert into personal (name, type, dni) values ('Inesita Huyghe', 'AYTO', '123456789B');
insert into personal (name, type, dni) values ('Faythe Dwelley', 'AYTO', '44555666E');
insert into personal (name, type, dni) values ('Rod Exley', 'MU', '11111111A');
insert into personal (name, type, dni) values ('Baxie Goodrum', 'AYTO', '11111111A');
insert into personal (name, type, dni) values ('Shayne Skull', 'VOL', '123456789B');
insert into personal (name, type, dni) values ('Grayce Gillard', 'VOL', '11111111A');
insert into personal (name, type, dni) values ('Rivi Duker', 'PC', '123456789B');
insert into personal (name, type, dni) values ('Charin Arrow', 'VOL', '11111111A');
insert into personal (name, type, dni) values ('Dana Muino', 'MU', '22333444C');
insert into personal (name, type, dni) values ('Will Burleigh', 'PC', '99000111K');
insert into personal (name, type, dni) values ('Celinka Tilston', 'AYTO', '88999000I');
insert into personal (name, type, dni) values ('Janey Meace', 'VOL', '99000111K');
insert into personal (name, type, dni) values ('Kingston Blackston', 'MU', '44555666E');
insert into personal (name, type, dni) values ('Mathian Pettyfar', 'AYTO', '99000111K');
insert into personal (name, type, dni) values ('Gale Vickerman', 'AYTO', '66777888G');
insert into personal (name, type, dni) values ('Sheba Tottie', 'AYTO', '44555666E');
insert into personal (name, type, dni) values ('Nollie Petto', 'PC', '77888999H');
insert into personal (name, type, dni) values ('Chastity Sisse', 'VOL', '55666777F');
insert into personal (name, type, dni) values ('Malanie Barrowclough', 'MU', '55666777F');
insert into personal (name, type, dni) values ('Lani Ismail', 'VOL', '55666777F');
insert into personal (name, type, dni) values ('Felice Althrop', 'AYTO', '33444555D');
insert into personal (name, type, dni) values ('Korrie Bovingdon', 'PL', '77888999H');
insert into personal (name, type, dni) values ('Timothee Danilowicz', 'AYTO', '44555666E');
insert into personal (name, type, dni) values ('Abdul Whitticks', 'VOL', '77888999H');
insert into personal (name, type, dni) values ('Dyanna Lewson', 'AYTO', '22333444C');
insert into personal (name, type, dni) values ('Gasparo Kun', 'AYTO', '123456789B');
insert into personal (name, type, dni) values ('Rowen Dorwood', 'MU', '44555666E');
insert into personal (name, type, dni) values ('Gussi Fendlow', 'PL', '55666777F');
insert into personal (name, type, dni) values ('Hillard Trengrouse', 'AYTO', '55666777F');
insert into personal (name, type, dni) values ('Gillan Vautrey', 'PC', '77888999H');
insert into personal (name, type, dni) values ('Osbourn Caiger', 'PL', '11111111A');
insert into personal (name, type, dni) values ('Tate Baynam', 'MU', '123456789B');
insert into personal (name, type, dni) values ('Brnaby Zorzoni', 'MU', '44555666E');
insert into personal (name, type, dni) values ('Win Boyen', 'PL', '55666777F');
insert into personal (name, type, dni) values ('Tabatha Dole', 'VOL', '33444555D');
insert into personal (name, type, dni) values ('Ronald Iceton', 'VOL', '44555666E');
insert into personal (name, type, dni) values ('Ware Ayscough', 'VOL', '55666777F');
insert into personal (name, type, dni) values ('Merwyn Rosenfelt', 'PL', '77888999H');
insert into personal (name, type, dni) values ('Annemarie Rissen', 'PL', '123456789B');
insert into personal (name, type, dni) values ('Zacharias Ellingham', 'PC', '11111111A');
insert into personal (name, type, dni) values ('Erina Mayze', 'PL', '123456789B');
insert into personal (name, type, dni) values ('Binni Elsop', 'VOL', '22333444C');
insert into personal (name, type, dni) values ('Emilee Lively', 'PC', '55666777F');
insert into personal (name, type, dni) values ('Genni Becarra', 'PC', '22333444C');
insert into personal (name, type, dni) values ('Manon McGucken', 'PL', '44555666E');
insert into personal (name, type, dni) values ('Blondell O''Scannill', 'MU', '55666777F');
insert into personal (name, type, dni) values ('Yard Goulborn', 'AYTO', '44555666E');
insert into personal (name, type, dni) values ('Laraine List', 'AYTO', '77888999H');

insert into personal_has_event (event_id, personal_id) values (3, 39);
insert into personal_has_event (event_id, personal_id) values (44, 53);
insert into personal_has_event (event_id, personal_id) values (10, 13);
insert into personal_has_event (event_id, personal_id) values (2, 86);
insert into personal_has_event (event_id, personal_id) values (21, 150);
insert into personal_has_event (event_id, personal_id) values (50, 81);
insert into personal_has_event (event_id, personal_id) values (36, 94);
insert into personal_has_event (event_id, personal_id) values (2, 152);
insert into personal_has_event (event_id, personal_id) values (19, 67);
insert into personal_has_event (event_id, personal_id) values (27, 102);
insert into personal_has_event (event_id, personal_id) values (20, 187);
insert into personal_has_event (event_id, personal_id) values (18, 180);
insert into personal_has_event (event_id, personal_id) values (20, 104);
insert into personal_has_event (event_id, personal_id) values (41, 151);
insert into personal_has_event (event_id, personal_id) values (48, 81);
insert into personal_has_event (event_id, personal_id) values (5, 192);
insert into personal_has_event (event_id, personal_id) values (25, 185);
insert into personal_has_event (event_id, personal_id) values (24, 2);
insert into personal_has_event (event_id, personal_id) values (42, 9);
insert into personal_has_event (event_id, personal_id) values (19, 50);
insert into personal_has_event (event_id, personal_id) values (9, 107);
insert into personal_has_event (event_id, personal_id) values (21, 114);
insert into personal_has_event (event_id, personal_id) values (49, 41);
insert into personal_has_event (event_id, personal_id) values (39, 81);
insert into personal_has_event (event_id, personal_id) values (21, 117);
insert into personal_has_event (event_id, personal_id) values (21, 168);
insert into personal_has_event (event_id, personal_id) values (33, 32);
insert into personal_has_event (event_id, personal_id) values (27, 30);
insert into personal_has_event (event_id, personal_id) values (11, 130);
insert into personal_has_event (event_id, personal_id) values (27, 53);
insert into personal_has_event (event_id, personal_id) values (5, 160);
insert into personal_has_event (event_id, personal_id) values (42, 157);
insert into personal_has_event (event_id, personal_id) values (44, 67);
insert into personal_has_event (event_id, personal_id) values (18, 19);
insert into personal_has_event (event_id, personal_id) values (50, 197);
insert into personal_has_event (event_id, personal_id) values (2, 4);
insert into personal_has_event (event_id, personal_id) values (8, 195);
insert into personal_has_event (event_id, personal_id) values (5, 118);
insert into personal_has_event (event_id, personal_id) values (38, 33);
insert into personal_has_event (event_id, personal_id) values (49, 194);
insert into personal_has_event (event_id, personal_id) values (2, 39);
insert into personal_has_event (event_id, personal_id) values (18, 110);
insert into personal_has_event (event_id, personal_id) values (17, 160);
insert into personal_has_event (event_id, personal_id) values (34, 186);
insert into personal_has_event (event_id, personal_id) values (16, 11);
insert into personal_has_event (event_id, personal_id) values (48, 137);
insert into personal_has_event (event_id, personal_id) values (30, 53);
insert into personal_has_event (event_id, personal_id) values (2, 68);
insert into personal_has_event (event_id, personal_id) values (21, 150);
insert into personal_has_event (event_id, personal_id) values (15, 88);
insert into personal_has_event (event_id, personal_id) values (18, 23);
insert into personal_has_event (event_id, personal_id) values (40, 87);
insert into personal_has_event (event_id, personal_id) values (45, 181);
insert into personal_has_event (event_id, personal_id) values (12, 200);
insert into personal_has_event (event_id, personal_id) values (4, 174);
insert into personal_has_event (event_id, personal_id) values (19, 169);
insert into personal_has_event (event_id, personal_id) values (22, 24);
insert into personal_has_event (event_id, personal_id) values (43, 10);
insert into personal_has_event (event_id, personal_id) values (33, 67);
insert into personal_has_event (event_id, personal_id) values (2, 112);
insert into personal_has_event (event_id, personal_id) values (14, 148);
insert into personal_has_event (event_id, personal_id) values (48, 25);
insert into personal_has_event (event_id, personal_id) values (33, 61);
insert into personal_has_event (event_id, personal_id) values (36, 188);
insert into personal_has_event (event_id, personal_id) values (29, 162);
insert into personal_has_event (event_id, personal_id) values (47, 126);
insert into personal_has_event (event_id, personal_id) values (39, 70);
insert into personal_has_event (event_id, personal_id) values (11, 7);
insert into personal_has_event (event_id, personal_id) values (26, 53);
insert into personal_has_event (event_id, personal_id) values (5, 79);
insert into personal_has_event (event_id, personal_id) values (27, 4);
insert into personal_has_event (event_id, personal_id) values (46, 111);
insert into personal_has_event (event_id, personal_id) values (23, 49);
insert into personal_has_event (event_id, personal_id) values (35, 51);
insert into personal_has_event (event_id, personal_id) values (14, 50);
insert into personal_has_event (event_id, personal_id) values (2, 49);
insert into personal_has_event (event_id, personal_id) values (31, 194);
insert into personal_has_event (event_id, personal_id) values (8, 134);
insert into personal_has_event (event_id, personal_id) values (38, 16);
insert into personal_has_event (event_id, personal_id) values (49, 186);
insert into personal_has_event (event_id, personal_id) values (34, 122);
insert into personal_has_event (event_id, personal_id) values (26, 39);
insert into personal_has_event (event_id, personal_id) values (11, 102);
insert into personal_has_event (event_id, personal_id) values (19, 199);
insert into personal_has_event (event_id, personal_id) values (15, 85);
insert into personal_has_event (event_id, personal_id) values (37, 88);
insert into personal_has_event (event_id, personal_id) values (1, 86);
insert into personal_has_event (event_id, personal_id) values (50, 151);
insert into personal_has_event (event_id, personal_id) values (44, 125);
insert into personal_has_event (event_id, personal_id) values (3, 155);
insert into personal_has_event (event_id, personal_id) values (24, 186);
insert into personal_has_event (event_id, personal_id) values (29, 131);
insert into personal_has_event (event_id, personal_id) values (8, 155);
insert into personal_has_event (event_id, personal_id) values (36, 147);
insert into personal_has_event (event_id, personal_id) values (11, 4);
insert into personal_has_event (event_id, personal_id) values (39, 128);
insert into personal_has_event (event_id, personal_id) values (40, 38);
insert into personal_has_event (event_id, personal_id) values (14, 134);
insert into personal_has_event (event_id, personal_id) values (31, 200);
insert into personal_has_event (event_id, personal_id) values (49, 176);
insert into personal_has_event (event_id, personal_id) values (19, 13);
insert into personal_has_event (event_id, personal_id) values (22, 135);
insert into personal_has_event (event_id, personal_id) values (19, 98);
insert into personal_has_event (event_id, personal_id) values (39, 185);
insert into personal_has_event (event_id, personal_id) values (4, 123);
insert into personal_has_event (event_id, personal_id) values (35, 89);
insert into personal_has_event (event_id, personal_id) values (13, 45);
insert into personal_has_event (event_id, personal_id) values (18, 46);
insert into personal_has_event (event_id, personal_id) values (46, 131);
insert into personal_has_event (event_id, personal_id) values (45, 186);
insert into personal_has_event (event_id, personal_id) values (13, 136);
insert into personal_has_event (event_id, personal_id) values (14, 196);
insert into personal_has_event (event_id, personal_id) values (7, 137);
insert into personal_has_event (event_id, personal_id) values (12, 160);
insert into personal_has_event (event_id, personal_id) values (44, 197);
insert into personal_has_event (event_id, personal_id) values (17, 26);
insert into personal_has_event (event_id, personal_id) values (36, 135);
insert into personal_has_event (event_id, personal_id) values (41, 124);
insert into personal_has_event (event_id, personal_id) values (38, 67);
insert into personal_has_event (event_id, personal_id) values (39, 54);
insert into personal_has_event (event_id, personal_id) values (8, 65);
insert into personal_has_event (event_id, personal_id) values (21, 148);
insert into personal_has_event (event_id, personal_id) values (19, 13);
insert into personal_has_event (event_id, personal_id) values (32, 8);
insert into personal_has_event (event_id, personal_id) values (31, 85);
insert into personal_has_event (event_id, personal_id) values (39, 90);
insert into personal_has_event (event_id, personal_id) values (13, 172);
insert into personal_has_event (event_id, personal_id) values (20, 95);
insert into personal_has_event (event_id, personal_id) values (20, 149);
insert into personal_has_event (event_id, personal_id) values (30, 150);
insert into personal_has_event (event_id, personal_id) values (21, 75);
insert into personal_has_event (event_id, personal_id) values (11, 27);
insert into personal_has_event (event_id, personal_id) values (39, 148);
insert into personal_has_event (event_id, personal_id) values (29, 46);
insert into personal_has_event (event_id, personal_id) values (42, 194);
insert into personal_has_event (event_id, personal_id) values (20, 5);
insert into personal_has_event (event_id, personal_id) values (30, 102);
insert into personal_has_event (event_id, personal_id) values (33, 149);
insert into personal_has_event (event_id, personal_id) values (39, 168);
insert into personal_has_event (event_id, personal_id) values (28, 176);
insert into personal_has_event (event_id, personal_id) values (24, 159);
insert into personal_has_event (event_id, personal_id) values (1, 120);
insert into personal_has_event (event_id, personal_id) values (34, 5);
insert into personal_has_event (event_id, personal_id) values (3, 159);
insert into personal_has_event (event_id, personal_id) values (4, 18);
insert into personal_has_event (event_id, personal_id) values (9, 146);
insert into personal_has_event (event_id, personal_id) values (47, 71);
insert into personal_has_event (event_id, personal_id) values (38, 38);
insert into personal_has_event (event_id, personal_id) values (5, 61);
insert into personal_has_event (event_id, personal_id) values (43, 24);
insert into personal_has_event (event_id, personal_id) values (41, 125);
insert into personal_has_event (event_id, personal_id) values (18, 126);
insert into personal_has_event (event_id, personal_id) values (6, 85);
insert into personal_has_event (event_id, personal_id) values (9, 199);
insert into personal_has_event (event_id, personal_id) values (45, 192);
insert into personal_has_event (event_id, personal_id) values (44, 78);
insert into personal_has_event (event_id, personal_id) values (42, 188);
insert into personal_has_event (event_id, personal_id) values (2, 40);
insert into personal_has_event (event_id, personal_id) values (27, 16);
insert into personal_has_event (event_id, personal_id) values (2, 22);
insert into personal_has_event (event_id, personal_id) values (41, 103);
insert into personal_has_event (event_id, personal_id) values (30, 174);
insert into personal_has_event (event_id, personal_id) values (14, 121);
insert into personal_has_event (event_id, personal_id) values (29, 183);
insert into personal_has_event (event_id, personal_id) values (22, 95);
insert into personal_has_event (event_id, personal_id) values (44, 141);
insert into personal_has_event (event_id, personal_id) values (24, 2);
insert into personal_has_event (event_id, personal_id) values (39, 16);
insert into personal_has_event (event_id, personal_id) values (37, 174);
insert into personal_has_event (event_id, personal_id) values (14, 185);
insert into personal_has_event (event_id, personal_id) values (23, 14);
insert into personal_has_event (event_id, personal_id) values (31, 66);
insert into personal_has_event (event_id, personal_id) values (37, 186);
insert into personal_has_event (event_id, personal_id) values (17, 5);
insert into personal_has_event (event_id, personal_id) values (3, 167);
insert into personal_has_event (event_id, personal_id) values (5, 22);
insert into personal_has_event (event_id, personal_id) values (26, 159);
insert into personal_has_event (event_id, personal_id) values (38, 31);
insert into personal_has_event (event_id, personal_id) values (36, 57);
insert into personal_has_event (event_id, personal_id) values (48, 11);
insert into personal_has_event (event_id, personal_id) values (22, 79);
insert into personal_has_event (event_id, personal_id) values (16, 68);
insert into personal_has_event (event_id, personal_id) values (23, 69);
insert into personal_has_event (event_id, personal_id) values (1, 72);
insert into personal_has_event (event_id, personal_id) values (3, 157);
insert into personal_has_event (event_id, personal_id) values (18, 67);
insert into personal_has_event (event_id, personal_id) values (12, 168);
insert into personal_has_event (event_id, personal_id) values (12, 152);
insert into personal_has_event (event_id, personal_id) values (16, 89);
insert into personal_has_event (event_id, personal_id) values (32, 50);
insert into personal_has_event (event_id, personal_id) values (26, 109);
insert into personal_has_event (event_id, personal_id) values (27, 138);
insert into personal_has_event (event_id, personal_id) values (5, 135);
insert into personal_has_event (event_id, personal_id) values (12, 13);
insert into personal_has_event (event_id, personal_id) values (12, 15);
insert into personal_has_event (event_id, personal_id) values (44, 83);
insert into personal_has_event (event_id, personal_id) values (40, 169);
insert into personal_has_event (event_id, personal_id) values (30, 90);
insert into personal_has_event (event_id, personal_id) values (35, 121);
insert into personal_has_event (event_id, personal_id) values (17, 7);
insert into personal_has_event (event_id, personal_id) values (27, 175);
insert into personal_has_event (event_id, personal_id) values (23, 65);
insert into personal_has_event (event_id, personal_id) values (44, 22);
insert into personal_has_event (event_id, personal_id) values (43, 68);
insert into personal_has_event (event_id, personal_id) values (18, 138);
insert into personal_has_event (event_id, personal_id) values (14, 25);
insert into personal_has_event (event_id, personal_id) values (47, 152);
insert into personal_has_event (event_id, personal_id) values (3, 118);
insert into personal_has_event (event_id, personal_id) values (23, 14);
insert into personal_has_event (event_id, personal_id) values (17, 74);
insert into personal_has_event (event_id, personal_id) values (8, 120);
insert into personal_has_event (event_id, personal_id) values (7, 62);
insert into personal_has_event (event_id, personal_id) values (11, 76);
insert into personal_has_event (event_id, personal_id) values (4, 58);
insert into personal_has_event (event_id, personal_id) values (46, 91);
insert into personal_has_event (event_id, personal_id) values (33, 179);
insert into personal_has_event (event_id, personal_id) values (41, 131);
insert into personal_has_event (event_id, personal_id) values (35, 2);
insert into personal_has_event (event_id, personal_id) values (20, 96);
insert into personal_has_event (event_id, personal_id) values (3, 77);
insert into personal_has_event (event_id, personal_id) values (35, 92);
insert into personal_has_event (event_id, personal_id) values (15, 2);
insert into personal_has_event (event_id, personal_id) values (43, 122);
insert into personal_has_event (event_id, personal_id) values (44, 20);
insert into personal_has_event (event_id, personal_id) values (17, 167);
insert into personal_has_event (event_id, personal_id) values (15, 109);
insert into personal_has_event (event_id, personal_id) values (33, 20);
insert into personal_has_event (event_id, personal_id) values (23, 103);
insert into personal_has_event (event_id, personal_id) values (23, 85);
insert into personal_has_event (event_id, personal_id) values (2, 33);
insert into personal_has_event (event_id, personal_id) values (35, 79);
insert into personal_has_event (event_id, personal_id) values (6, 47);
insert into personal_has_event (event_id, personal_id) values (31, 149);
insert into personal_has_event (event_id, personal_id) values (11, 56);
insert into personal_has_event (event_id, personal_id) values (7, 169);
insert into personal_has_event (event_id, personal_id) values (46, 140);
insert into personal_has_event (event_id, personal_id) values (50, 116);
insert into personal_has_event (event_id, personal_id) values (7, 109);
insert into personal_has_event (event_id, personal_id) values (32, 92);
insert into personal_has_event (event_id, personal_id) values (37, 4);
insert into personal_has_event (event_id, personal_id) values (39, 56);
insert into personal_has_event (event_id, personal_id) values (30, 195);
insert into personal_has_event (event_id, personal_id) values (34, 13);
insert into personal_has_event (event_id, personal_id) values (30, 3);
insert into personal_has_event (event_id, personal_id) values (38, 2);
insert into personal_has_event (event_id, personal_id) values (23, 164);
insert into personal_has_event (event_id, personal_id) values (46, 85);
insert into personal_has_event (event_id, personal_id) values (34, 192);
insert into personal_has_event (event_id, personal_id) values (31, 103);
insert into personal_has_event (event_id, personal_id) values (38, 40);
insert into personal_has_event (event_id, personal_id) values (24, 88);
insert into personal_has_event (event_id, personal_id) values (5, 127);
insert into personal_has_event (event_id, personal_id) values (31, 5);
insert into personal_has_event (event_id, personal_id) values (13, 12);
insert into personal_has_event (event_id, personal_id) values (42, 20);
insert into personal_has_event (event_id, personal_id) values (21, 106);
insert into personal_has_event (event_id, personal_id) values (3, 88);
insert into personal_has_event (event_id, personal_id) values (31, 91);
insert into personal_has_event (event_id, personal_id) values (39, 115);
insert into personal_has_event (event_id, personal_id) values (49, 38);
insert into personal_has_event (event_id, personal_id) values (47, 158);
insert into personal_has_event (event_id, personal_id) values (32, 88);
insert into personal_has_event (event_id, personal_id) values (37, 175);
insert into personal_has_event (event_id, personal_id) values (26, 1);
insert into personal_has_event (event_id, personal_id) values (30, 66);
insert into personal_has_event (event_id, personal_id) values (25, 137);
insert into personal_has_event (event_id, personal_id) values (6, 112);
insert into personal_has_event (event_id, personal_id) values (12, 195);
insert into personal_has_event (event_id, personal_id) values (15, 177);
insert into personal_has_event (event_id, personal_id) values (28, 74);
insert into personal_has_event (event_id, personal_id) values (23, 8);
insert into personal_has_event (event_id, personal_id) values (46, 148);
insert into personal_has_event (event_id, personal_id) values (13, 72);
insert into personal_has_event (event_id, personal_id) values (33, 63);
insert into personal_has_event (event_id, personal_id) values (18, 44);
insert into personal_has_event (event_id, personal_id) values (18, 152);
insert into personal_has_event (event_id, personal_id) values (5, 132);
insert into personal_has_event (event_id, personal_id) values (48, 13);
insert into personal_has_event (event_id, personal_id) values (12, 35);
insert into personal_has_event (event_id, personal_id) values (16, 137);
insert into personal_has_event (event_id, personal_id) values (8, 199);
insert into personal_has_event (event_id, personal_id) values (40, 28);
insert into personal_has_event (event_id, personal_id) values (23, 123);
insert into personal_has_event (event_id, personal_id) values (49, 132);
insert into personal_has_event (event_id, personal_id) values (8, 39);
insert into personal_has_event (event_id, personal_id) values (20, 73);
insert into personal_has_event (event_id, personal_id) values (3, 47);
insert into personal_has_event (event_id, personal_id) values (19, 63);
insert into personal_has_event (event_id, personal_id) values (13, 110);
insert into personal_has_event (event_id, personal_id) values (18, 53);
insert into personal_has_event (event_id, personal_id) values (50, 172);
insert into personal_has_event (event_id, personal_id) values (23, 192);
insert into personal_has_event (event_id, personal_id) values (31, 199);
insert into personal_has_event (event_id, personal_id) values (38, 86);
insert into personal_has_event (event_id, personal_id) values (27, 87);
insert into personal_has_event (event_id, personal_id) values (34, 34);
insert into personal_has_event (event_id, personal_id) values (42, 121);
insert into personal_has_event (event_id, personal_id) values (44, 187);
insert into personal_has_event (event_id, personal_id) values (10, 79);
insert into personal_has_event (event_id, personal_id) values (18, 19);
insert into personal_has_event (event_id, personal_id) values (23, 156);
insert into personal_has_event (event_id, personal_id) values (18, 58);
insert into personal_has_event (event_id, personal_id) values (46, 162);
insert into personal_has_event (event_id, personal_id) values (47, 196);
insert into personal_has_event (event_id, personal_id) values (37, 93);
insert into personal_has_event (event_id, personal_id) values (4, 187);
insert into personal_has_event (event_id, personal_id) values (7, 109);
insert into personal_has_event (event_id, personal_id) values (27, 177);
insert into personal_has_event (event_id, personal_id) values (2, 115);
insert into personal_has_event (event_id, personal_id) values (20, 113);
insert into personal_has_event (event_id, personal_id) values (41, 144);
insert into personal_has_event (event_id, personal_id) values (12, 198);
insert into personal_has_event (event_id, personal_id) values (1, 31);
insert into personal_has_event (event_id, personal_id) values (26, 149);
insert into personal_has_event (event_id, personal_id) values (28, 113);
insert into personal_has_event (event_id, personal_id) values (23, 41);
insert into personal_has_event (event_id, personal_id) values (4, 158);
insert into personal_has_event (event_id, personal_id) values (40, 182);
insert into personal_has_event (event_id, personal_id) values (28, 32);
insert into personal_has_event (event_id, personal_id) values (6, 101);
insert into personal_has_event (event_id, personal_id) values (42, 39);
insert into personal_has_event (event_id, personal_id) values (39, 152);
insert into personal_has_event (event_id, personal_id) values (9, 54);
insert into personal_has_event (event_id, personal_id) values (17, 83);
insert into personal_has_event (event_id, personal_id) values (18, 142);
insert into personal_has_event (event_id, personal_id) values (37, 109);
insert into personal_has_event (event_id, personal_id) values (24, 19);
insert into personal_has_event (event_id, personal_id) values (45, 177);
insert into personal_has_event (event_id, personal_id) values (41, 138);
insert into personal_has_event (event_id, personal_id) values (16, 146);
insert into personal_has_event (event_id, personal_id) values (4, 167);
insert into personal_has_event (event_id, personal_id) values (40, 143);
insert into personal_has_event (event_id, personal_id) values (9, 126);
insert into personal_has_event (event_id, personal_id) values (3, 39);
insert into personal_has_event (event_id, personal_id) values (12, 109);
insert into personal_has_event (event_id, personal_id) values (32, 79);
insert into personal_has_event (event_id, personal_id) values (39, 2);
insert into personal_has_event (event_id, personal_id) values (20, 154);
insert into personal_has_event (event_id, personal_id) values (4, 55);
insert into personal_has_event (event_id, personal_id) values (19, 81);
insert into personal_has_event (event_id, personal_id) values (44, 196);
insert into personal_has_event (event_id, personal_id) values (31, 7);
insert into personal_has_event (event_id, personal_id) values (38, 165);
insert into personal_has_event (event_id, personal_id) values (37, 77);
insert into personal_has_event (event_id, personal_id) values (4, 10);
insert into personal_has_event (event_id, personal_id) values (45, 134);
insert into personal_has_event (event_id, personal_id) values (49, 133);
insert into personal_has_event (event_id, personal_id) values (10, 172);
insert into personal_has_event (event_id, personal_id) values (27, 198);
insert into personal_has_event (event_id, personal_id) values (17, 148);
insert into personal_has_event (event_id, personal_id) values (21, 61);
insert into personal_has_event (event_id, personal_id) values (32, 99);
insert into personal_has_event (event_id, personal_id) values (10, 192);
insert into personal_has_event (event_id, personal_id) values (25, 102);
insert into personal_has_event (event_id, personal_id) values (35, 32);
insert into personal_has_event (event_id, personal_id) values (35, 141);
insert into personal_has_event (event_id, personal_id) values (6, 148);
insert into personal_has_event (event_id, personal_id) values (23, 12);
insert into personal_has_event (event_id, personal_id) values (7, 118);
insert into personal_has_event (event_id, personal_id) values (49, 52);
insert into personal_has_event (event_id, personal_id) values (48, 154);
insert into personal_has_event (event_id, personal_id) values (39, 85);
insert into personal_has_event (event_id, personal_id) values (10, 152);
insert into personal_has_event (event_id, personal_id) values (38, 135);
insert into personal_has_event (event_id, personal_id) values (10, 192);
insert into personal_has_event (event_id, personal_id) values (16, 111);
insert into personal_has_event (event_id, personal_id) values (2, 104);
insert into personal_has_event (event_id, personal_id) values (44, 66);
insert into personal_has_event (event_id, personal_id) values (17, 135);
insert into personal_has_event (event_id, personal_id) values (38, 132);
insert into personal_has_event (event_id, personal_id) values (40, 176);
insert into personal_has_event (event_id, personal_id) values (26, 53);
insert into personal_has_event (event_id, personal_id) values (28, 145);
insert into personal_has_event (event_id, personal_id) values (31, 73);
insert into personal_has_event (event_id, personal_id) values (38, 43);
insert into personal_has_event (event_id, personal_id) values (32, 171);
insert into personal_has_event (event_id, personal_id) values (35, 122);
insert into personal_has_event (event_id, personal_id) values (43, 72);
insert into personal_has_event (event_id, personal_id) values (34, 168);
insert into personal_has_event (event_id, personal_id) values (4, 26);
insert into personal_has_event (event_id, personal_id) values (47, 180);
insert into personal_has_event (event_id, personal_id) values (12, 181);
insert into personal_has_event (event_id, personal_id) values (22, 10);
insert into personal_has_event (event_id, personal_id) values (5, 162);
insert into personal_has_event (event_id, personal_id) values (15, 53);
insert into personal_has_event (event_id, personal_id) values (11, 36);
insert into personal_has_event (event_id, personal_id) values (43, 65);
insert into personal_has_event (event_id, personal_id) values (46, 76);
insert into personal_has_event (event_id, personal_id) values (22, 107);
insert into personal_has_event (event_id, personal_id) values (22, 49);
insert into personal_has_event (event_id, personal_id) values (18, 100);
insert into personal_has_event (event_id, personal_id) values (18, 60);
insert into personal_has_event (event_id, personal_id) values (44, 38);
insert into personal_has_event (event_id, personal_id) values (37, 75);
insert into personal_has_event (event_id, personal_id) values (39, 168);
insert into personal_has_event (event_id, personal_id) values (26, 93);
insert into personal_has_event (event_id, personal_id) values (8, 79);
insert into personal_has_event (event_id, personal_id) values (13, 113);
insert into personal_has_event (event_id, personal_id) values (9, 19);
insert into personal_has_event (event_id, personal_id) values (17, 161);
insert into personal_has_event (event_id, personal_id) values (11, 80);
insert into personal_has_event (event_id, personal_id) values (12, 162);
insert into personal_has_event (event_id, personal_id) values (6, 187);
insert into personal_has_event (event_id, personal_id) values (31, 189);
insert into personal_has_event (event_id, personal_id) values (25, 177);
insert into personal_has_event (event_id, personal_id) values (26, 133);
insert into personal_has_event (event_id, personal_id) values (45, 35);
insert into personal_has_event (event_id, personal_id) values (16, 123);
insert into personal_has_event (event_id, personal_id) values (31, 4);
insert into personal_has_event (event_id, personal_id) values (27, 142);
insert into personal_has_event (event_id, personal_id) values (20, 122);
insert into personal_has_event (event_id, personal_id) values (8, 108);
insert into personal_has_event (event_id, personal_id) values (49, 38);
insert into personal_has_event (event_id, personal_id) values (27, 58);
insert into personal_has_event (event_id, personal_id) values (6, 166);
insert into personal_has_event (event_id, personal_id) values (50, 124);
insert into personal_has_event (event_id, personal_id) values (40, 159);
insert into personal_has_event (event_id, personal_id) values (36, 8);
insert into personal_has_event (event_id, personal_id) values (43, 16);
insert into personal_has_event (event_id, personal_id) values (37, 184);
insert into personal_has_event (event_id, personal_id) values (26, 132);
insert into personal_has_event (event_id, personal_id) values (8, 153);
insert into personal_has_event (event_id, personal_id) values (27, 36);
insert into personal_has_event (event_id, personal_id) values (4, 48);
insert into personal_has_event (event_id, personal_id) values (4, 48);
insert into personal_has_event (event_id, personal_id) values (50, 60);
insert into personal_has_event (event_id, personal_id) values (9, 33);
insert into personal_has_event (event_id, personal_id) values (36, 19);
insert into personal_has_event (event_id, personal_id) values (30, 127);
insert into personal_has_event (event_id, personal_id) values (35, 168);
insert into personal_has_event (event_id, personal_id) values (21, 30);
insert into personal_has_event (event_id, personal_id) values (3, 175);
insert into personal_has_event (event_id, personal_id) values (44, 134);
insert into personal_has_event (event_id, personal_id) values (2, 103);
insert into personal_has_event (event_id, personal_id) values (46, 29);
insert into personal_has_event (event_id, personal_id) values (15, 157);
insert into personal_has_event (event_id, personal_id) values (13, 60);
insert into personal_has_event (event_id, personal_id) values (15, 152);
insert into personal_has_event (event_id, personal_id) values (35, 133);
insert into personal_has_event (event_id, personal_id) values (13, 102);
insert into personal_has_event (event_id, personal_id) values (48, 115);
insert into personal_has_event (event_id, personal_id) values (1, 32);
insert into personal_has_event (event_id, personal_id) values (5, 172);
insert into personal_has_event (event_id, personal_id) values (20, 52);
insert into personal_has_event (event_id, personal_id) values (8, 62);
insert into personal_has_event (event_id, personal_id) values (4, 77);
insert into personal_has_event (event_id, personal_id) values (48, 94);
insert into personal_has_event (event_id, personal_id) values (46, 132);
insert into personal_has_event (event_id, personal_id) values (45, 193);
insert into personal_has_event (event_id, personal_id) values (41, 123);
insert into personal_has_event (event_id, personal_id) values (29, 25);
insert into personal_has_event (event_id, personal_id) values (18, 86);
insert into personal_has_event (event_id, personal_id) values (20, 119);
insert into personal_has_event (event_id, personal_id) values (36, 11);
insert into personal_has_event (event_id, personal_id) values (7, 7);
insert into personal_has_event (event_id, personal_id) values (36, 117);
insert into personal_has_event (event_id, personal_id) values (17, 200);
insert into personal_has_event (event_id, personal_id) values (43, 46);
insert into personal_has_event (event_id, personal_id) values (7, 151);
insert into personal_has_event (event_id, personal_id) values (30, 153);
insert into personal_has_event (event_id, personal_id) values (5, 132);
insert into personal_has_event (event_id, personal_id) values (47, 153);
insert into personal_has_event (event_id, personal_id) values (44, 116);
insert into personal_has_event (event_id, personal_id) values (7, 39);
insert into personal_has_event (event_id, personal_id) values (21, 16);
insert into personal_has_event (event_id, personal_id) values (27, 38);
insert into personal_has_event (event_id, personal_id) values (21, 12);
insert into personal_has_event (event_id, personal_id) values (37, 109);
insert into personal_has_event (event_id, personal_id) values (35, 2);
insert into personal_has_event (event_id, personal_id) values (34, 176);
insert into personal_has_event (event_id, personal_id) values (39, 160);
insert into personal_has_event (event_id, personal_id) values (49, 39);
insert into personal_has_event (event_id, personal_id) values (27, 159);
insert into personal_has_event (event_id, personal_id) values (45, 110);
insert into personal_has_event (event_id, personal_id) values (39, 106);
insert into personal_has_event (event_id, personal_id) values (18, 42);
insert into personal_has_event (event_id, personal_id) values (26, 16);
insert into personal_has_event (event_id, personal_id) values (36, 89);
insert into personal_has_event (event_id, personal_id) values (46, 120);
insert into personal_has_event (event_id, personal_id) values (17, 197);
insert into personal_has_event (event_id, personal_id) values (50, 76);
insert into personal_has_event (event_id, personal_id) values (21, 124);
insert into personal_has_event (event_id, personal_id) values (28, 183);
insert into personal_has_event (event_id, personal_id) values (40, 72);
insert into personal_has_event (event_id, personal_id) values (44, 69);
insert into personal_has_event (event_id, personal_id) values (14, 141);
insert into personal_has_event (event_id, personal_id) values (34, 120);
insert into personal_has_event (event_id, personal_id) values (42, 3);
insert into personal_has_event (event_id, personal_id) values (47, 134);
insert into personal_has_event (event_id, personal_id) values (8, 61);
insert into personal_has_event (event_id, personal_id) values (25, 92);
insert into personal_has_event (event_id, personal_id) values (8, 94);
insert into personal_has_event (event_id, personal_id) values (16, 6);
insert into personal_has_event (event_id, personal_id) values (35, 148);
insert into personal_has_event (event_id, personal_id) values (16, 82);
insert into personal_has_event (event_id, personal_id) values (5, 18);
insert into personal_has_event (event_id, personal_id) values (34, 161);
insert into personal_has_event (event_id, personal_id) values (37, 91);
insert into personal_has_event (event_id, personal_id) values (17, 144);
insert into personal_has_event (event_id, personal_id) values (16, 154);
